### ---------------------------------------------------
### ---------------------- EVENTS ---------------------
### ---------------------------------------------------


### Create a new event
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New Event",
    "date": "2017-01-01T00:00:00",
    "price": 100,
    "description": "This is a new event"
}
###

@eventId = {{ createEvent.response.body.id }}

### Get all events
GET http://localhost:3000/events

### Get unique event
GET http://localhost:3000/events/{{ eventId }}

### Edit event by id
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
    "name": "New Event - edited",
    "date": "2017-01-01T00:00:00",
    "price": 100,
    "description": "This is a new event"
}

### Delete event by id
DELETE http://localhost:3000/events/{{ eventId }}


### Get all spots by event id
GET http://localhost:3000/events/{{eventId}}/spots

### ---------------------------------------------------
### ---------------------- SPOTS ----------------------
### ---------------------------------------------------


### Create spot by event id
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A3"
}

###

@spotId = {{ createSpot.response.body.id }}

### Get all spots
GET http://localhost:3000/events/{{ eventId }}/spots

### Get unique spot
GET http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}

### Edit spot by id
PATCH http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}
Content-Type: application/json

{
  "name": "A1"
}

### Delete event by id
DELETE http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}
