### Create a new event
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New Event",
    "date": "2017-01-01T00:00:00",
    "price": 100,
    "description": "This is a new event"
}
###

@eventId = {{ createEvent.response.body.id }}

### Get all events
GET http://localhost:3000/events

### Get unique event
GET http://localhost:3000/events/{{ eventId }}

### Edit event by id
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
    "name": "New Event - edited",
    "date": "2017-01-01T00:00:00",
    "price": 100,
    "description": "This is a new event"
}

### Delete event by id
DELETE http://localhost:3000/events/{{ eventId }}